// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3NfgOW8Ca6NvnvsVxTDQTClF0ez_cIxA',
    appId: '1:8608006827:web:b31af485fb6e81ac2a6dee',
    messagingSenderId: '8608006827',
    projectId: 'taskmanagment-80b42',
    authDomain: 'taskmanagment-80b42.firebaseapp.com',
    storageBucket: 'taskmanagment-80b42.appspot.com',
    measurementId: 'G-VCW6BG0KBJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAawr4cPlTgW8mbC0nkvxdhKw3HibzlFd4',
    appId: '1:8608006827:android:46b717026f5c7cf02a6dee',
    messagingSenderId: '8608006827',
    projectId: 'taskmanagment-80b42',
    storageBucket: 'taskmanagment-80b42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf6MjxOWUlz5UxIIXId9m4hug5vnaoVd0',
    appId: '1:8608006827:ios:90e59d20eb6d005a2a6dee',
    messagingSenderId: '8608006827',
    projectId: 'taskmanagment-80b42',
    storageBucket: 'taskmanagment-80b42.appspot.com',
    iosBundleId: 'com.example.sampleInhouse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf6MjxOWUlz5UxIIXId9m4hug5vnaoVd0',
    appId: '1:8608006827:ios:90e59d20eb6d005a2a6dee',
    messagingSenderId: '8608006827',
    projectId: 'taskmanagment-80b42',
    storageBucket: 'taskmanagment-80b42.appspot.com',
    iosBundleId: 'com.example.sampleInhouse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3NfgOW8Ca6NvnvsVxTDQTClF0ez_cIxA',
    appId: '1:8608006827:web:14f641acde053a782a6dee',
    messagingSenderId: '8608006827',
    projectId: 'taskmanagment-80b42',
    authDomain: 'taskmanagment-80b42.firebaseapp.com',
    storageBucket: 'taskmanagment-80b42.appspot.com',
    measurementId: 'G-3YK6Z2T7H2',
  );
}
